import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const OpenSans = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UEN Expedito Cortez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${OpenSans.className} antialiased bg-gray-100 w-full grid min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
